### ISSUE TITLE
After the conversion, the map is wrong.

### ISSUE THREAD

**Issue by zxl777** [ljyloo/LevelDb2Avnil#12]
After the conversion, the map with PocketMine loaded.
![img_4092](https://cloud.githubusercontent.com/assets/816448/11064873/e9973850-87fa-11e5-917e-5dd2b327d786.PNG)

The original map screenshot.
![ok](https://cloud.githubusercontent.com/assets/816448/11064984/a97ed948-87fb-11e5-83bd-213da8a3db9e.PNG)

the original world zip file
![world pe leveldb zip](https://cloud.githubusercontent.com/assets/816448/11064517/9517afbe-87f8-11e5-95f5-2f49e6d3d36d.png)
Please download the .png file then rename to .zip & unzip the world.
https://cloud.githubusercontent.com/assets/816448/11064517/9517afbe-87f8-11e5-95f5-2f49e6d3d36d.png

**Comment by keithkfng** [comment]
I think your level.dat file is causing a problem. Please ask @ljyloo, but if he doesn't reply, contact me directly, and I'll tell him via Twitter.

**Comment by Striker209** [comment]
Hi @keithkfng, I also have the same problem

Strange surrounding chunks are due to PocketMine it self so I don't report this as an error

But the real bugs after converting are:
- No chests
- No signs
==> No tiles at all?
- Dark grass (block data not converted?)
- Coordinates (X, Y, Z) are TOTALLY DIFFERENT! (maybe there is a translation vector between the source world and the converted one?)

Thanks for taking the time to investigate in this!

**Comment by Samueljh1** [comment]
Nope the issue is you have not generated enough chunks when you made the level. Go back into the original and fly around a bit to generate chunks. The reason these columns are there is because your server is then generating new chunks as you fly around (or spawn in) - these are high up because the server has a different generator (and settings) than MCPE

**Comment by ljyloo** [comment]
Fixed.
